CREATE SEQUENCE SEQ_TIPO;
CREATE SEQUENCE SEQ_HEROI;
CREATE SEQUENCE SEQ_GRUPO;
CREATE TABLE TIPO(
IDTIPO NUMBER(15) NOT NULL,
NOME VARCHAR2(50) NOT NULL
);
ALTER TABLE TIPO
ADD CONSTRAINT PK_TIPO PRIMARY KEY (IDTIPO); 
CREATE TABLE HEROI(
IDHEROI NUMBER(15) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
IDENTIDADE VARCHAR2(50) NOT NULL,
PODER VARCHAR2(50) NOT NULL,
IDTIPO NUMBER(15) NOT NULL
);
ALTER TABLE HEROI
ADD CONSTRAINT PK_HERO PRIMARY KEY (IDHEROI);
ALTER TABLE HEROI
ADD CONSTRAINT FK_TIPOHERO FOREIGN KEY (IDTIPO) REFERENCES TIPO
(IDTIPO);
CREATE TABLE GRUPO(
IDGRUPO NUMBER(15) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
IDTIPO NUMBER(15) NOT NULL
);
ALTER TABLE GRUPO
ADD CONSTRAINT PK_GRUPO PRIMARY KEY (IDGRUPO);
ALTER TABLE GRUPO
ADD CONSTRAINT FK_TIPOGRUPO FOREIGN KEY (IDTIPO) REFERENCES TIPO
(IDTIPO);
CREATE TABLE HEROIGRUPO(
IDHEROI NUMBER(15),
IDGRUPO NUMBER(15)
);
ALTER TABLE HEROIGRUPO
ADD CONSTRAINT PK_HEROIGRUPO PRIMARY KEY (IDGRUPO,IDHEROI);
ALTER TABLE HEROIGRUPO
ADD CONSTRAINT FK_HEROIGRUPO1 FOREIGN KEY (IDGRUPO) REFERENCES GRUPO
(IDGRUPO);
ALTER TABLE HEROIGRUPO
ADD CONSTRAINT FK_HEROIGRUPO2 FOREIGN KEY (IDHEROI) REFERENCES HEROI
(IDHEROI);
INSERT INTO TIPO(IDTIPO, NOME)
VALUES (SEQ_TIPO.NEXTVAL, 'Heroi');
INSERT INTO TIPO(IDTIPO, NOME)
VALUES (SEQ_TIPO.NEXTVAL, 'Vilão');
COMMIT;
